config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :recipes
  root 'recipes#index'
end

app/models/direction.rb
class Direction < ActiveRecord::Base
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
    belongs_to :user
    has_many :ingredients
    has_many :directions
    accepts_nested_attributes_for :ingredients,
                                                reject_if: proc { |attributes| attributes['name'].blank? },
                                                allow_destroy: true
 	accepts_nested_attributes_for :directions,
 	                                            reject_if: proc { |attributes| attributes['step'].blank? },
 	                                            allow_destroy: true
 	                                            
 	validates :title, :description, :image, presence: true
  
    has_attached_file :image, styles: { medium: "400x400#"}, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :find_recipe, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except:[:index, :show]
    def index
        @recipes = Recipe.all.order("created_at DESC")
    end
    
    def show
    end
    
    def new
        @recipe = current_user.recipes.build
    end
    
    def create
        @recipe = current_user.recipes.build(recipe_params)
        if @recipe.save
            redirect_to @recipe
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @recipe.update(recipe_params)
            redirect_to @recipe
        else
            render 'edit'
        end
    end
    
    def destroy
        @recipe.destroy
        redirect_to root_path, notice: "Borrado satisfactoriamente"
    end
    
    private
    
    def find_recipe
        @recipe = Recipe.find(params[:id])
    end
    
    def recipe_params
        params.require(:recipe).permit(:title, :description, :image, ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :step, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.haml
!!! 5
%html
%head
  %title Recetas
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to "Las Recetas", root_path
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Nueva Receta", new_recipe_path
          %li= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete
      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Registrarse", new_user_registration_path
          %li= link_to "Iniciar Sesión", new_user_session_path
        
  .container
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert"
    = yield

app/views/recipes/_direction_fields.haml
.form-inline.clearfix
    .nested-fields
        = f.input :step, input_html: {class:'form-input form-control'}
        = link_to_remove_association "Eliminar", f, class: "form-button btn btn-default"

app/views/recipes/_form.haml
= simple_form_for @recipe, html: {multipart: true} do |f|
    .panel-body
        = f.input :title, input_html: {class: 'form-control'}
        = f.input :description, input_html: {class: 'form-control'}
        = f.input :image, input_html: {class: 'form-control'}
        
    .row
        .col-md-6
            %h3 Ingredientes
            #ingredients
                = f.simple_fields_for :ingredients do |ingredient|
                    = render 'ingredient_fields', f: ingredient
                .links
                    = link_to_add_association 'Agregar Ingrediente', f, :ingredients, class: 'btn btn-primary add-button'
        .col-md-6
            %h3 Pasos
            #directions
                = f.simple_fields_for :directions do |direction|
                    = render 'direction_fields', f: direction 
                .links
                    = link_to_add_association 'Agregar Paso', f, :directions, class: 'btn btn-primary add-button'
    =f.button :submit, 'Guardar', class: 'btn btn-primary'

app/views/recipes/_ingredient_fields.haml
.form-inline.clearfix
    .nested-fields
        = f.input :name, input_html: {class:'form-input form-control'}
        = link_to_remove_association "Eliminar", f, class: "form-button btn btn-default"

app/views/recipes/edit.haml
%h1 Editando receta
= render 'form'

app/views/recipes/index.haml
- @recipes.each_slice(3) do |recipes|
    .row
        - recipes.each do |recipe|
            .col-md-4
                .recipe
                    .image_wrapper
                        = link_to recipe do
                            = image_tag recipe.image.url(:medium)
                    %h2= link_to recipe.title, recipe

app/views/recipes/new.haml
%h1 Nueva Receta
= render 'form'

app/views/recipes/show.haml
.main_content
    .recipe_top.row
        .col-md-4
            = image_tag @recipe.image.url(:medium), class: 'recipe_image'
        .col-md-8
            #recipe_info
                %h1= @recipe.title
                %p.description= @recipe.description
    .row
        .col-md-6
            #ingredients
                %h2 Ingredientes
                %ul
                    - @recipe.ingredients.each do |ingredient|
                        %li= ingredient.name
        .col-md-6
            #directions
                %h2 Instrucciones
                %ul
                    - @recipe.directions.each do |direction|
                        %li= direction.step
        
- if user_signed_in?
    = link_to 'Editar', edit_recipe_path, class: "btn btn-default"
    = link_to 'Borrar', recipe_path, method: :delete, data:{confirm: "Estas seguro?"}, class: "btn btn-default"